import type { IconType } from 'react-icons';
import {
  RiAddLine,
  RiAlertLine,
  RiArrowDropDownLine,
  RiArrowRightLine,
  RiArrowUpDownLine,
  RiBold,
  RiCalendarLine,
  RiChat1Line,
  RiCheckboxBlankLine,
  RiCheckboxFill,
  RiCheckLine,
  RiCircleLine,
  RiCloseLine,
  RiCloudOffLine,
  RiDeleteBinLine,
  RiErrorWarningLine,
  RiEyeLine,
  RiEyeOffLine,
  RiHome2Line,
  RiImage2Line,
  RiInformation2Line,
  RiItalic,
  RiLoader2Line,
  RiLoader4Line,
  RiLoader5Line,
  RiLogoutBoxRLine,
  RiLoopRightLine,
  RiMedicineBottleLine,
  RiMenLine,
  RiMentalHealthLine,
  RiPagesLine,
  RiPencilLine,
  RiRadioButtonLine,
  RiSaveLine,
  RiSearch2Line,
  RiSortAsc,
  RiSortDesc,
  RiStarFill,
  RiStarHalfLine,
  RiStarLine,
  RiSubtractLine,
  RiSurveyLine,
  RiUpload2Line,
  RiUserHeartLine,
  RiWomenLine,
} from 'react-icons/ri';

export type FaIconType = IconType;

export const FaIcon = {
  Alert: RiAlertLine,
  ArrowDropDown: RiArrowDropDownLine,
  ArrowRight: RiArrowRightLine,
  Bold: RiBold,
  Calendar: RiCalendarLine,
  Circle: RiCircleLine,
  CircleFill: RiRadioButtonLine,
  Chat: RiChat1Line,
  Check: RiCheckLine,
  CheckboxEmpty: RiCheckboxBlankLine,
  CheckboxFill: RiCheckboxFill,
  Close: RiCloseLine,
  CloudOff: RiCloudOffLine,
  Consultation: RiMedicineBottleLine,
  Edit: RiPencilLine,
  Empty: RiCircleLine,
  Error: RiErrorWarningLine,
  Female: RiWomenLine,
  FileUpload: RiUpload2Line,
  FlashAlert: RiAlertLine,
  FlashInfo: RiInformation2Line,
  FlashSuccess: RiCheckLine,
  FlashWarning: RiErrorWarningLine,
  Form: RiPagesLine,
  Home: RiHome2Line,
  Image: RiImage2Line,
  Info: RiInformation2Line,
  Italic: RiItalic,
  LoaderCircle: RiLoader4Line,
  LoaderCog: RiLoader2Line,
  LoaderSpinner: RiLoader5Line,
  LoaderSync: RiLoopRightLine,
  Male: RiMenLine,
  Mother: RiUserHeartLine,
  PasswordHide: RiEyeOffLine,
  PasswordShow: RiEyeLine,
  Patients: RiMentalHealthLine,
  Plus: RiAddLine,
  Save: RiSaveLine,
  Search: RiSearch2Line,
  SignOut: RiLogoutBoxRLine,
  SortAsc: RiSortAsc,
  SortDesc: RiSortDesc,
  SortUpDown: RiArrowUpDownLine,
  Star: RiStarLine,
  StarFull: RiStarFill,
  StarHalf: RiStarHalfLine,
  StepperMinus: RiSubtractLine,
  StepperPlus: RiAddLine,
  Survey: RiSurveyLine,
  Trash: RiDeleteBinLine,
};
