name: Lint and Build

on:
  - pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get NODE_VERSION from .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Install npm dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Copy environment variable
        run: cp .env.sample .env

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:4000'

    timeout-minutes: 10
